#!/usr/bin/python3

import sys, drawblockdiag, tokenize, parse, grammarutil, json, os

string=open(sys.argv[1], 'r').read()

tokens=tokenize.tokenize(string)
#print(tokens)
with open('tokens.txt', 'w') as fd:
	fd.write("\n".join(str(t) for t in tokens))
node=parse.parse(tokens)

drawblockdiag.emit_node_file(open('out.bd', 'w'), node, portrait_mode=True)

#print("===")

import transform, transformer

#print(transform.transformers)

with open("out.ll", 'w') as fd:
	e=transform.Emitter(fd)
	with e.scope():
		with e.context(file="in"):
			transform.emit(e, node)
	e.emit_global_statments()

os.system("llc out.ll;gcc -o out out.s; rm out.s; ./out")