#!/bin/bash

export PATH=$PATH:~/orth/compiler

cd src

orthc shoc.ort nobuild nolink
clang -S out.ll
gcc -L/usr/local/lib -I/usr/local/include ../../lib/re/headerstub.c headerstub.c out.s -lpcre2-8 -o out